### ISSUE TITLE
Fetcher failure

### ISSUE THREAD

**Issue by skypap** [landgraf/moelinux#1]
I did the fallowing 

mkdir moelinux
cd moelinux
repo init -u https://github.com/landgraf/moelinux.git
repo sync --no-clone-bundle
TEMPLATECONF="../meta-moelinux/conf/templates/moelinux/" . ./core/oe-init-build-env 
bitbake `moelinux-image-base

and I'm getting this issue :

WARNING: u-boot-allwinnerd1-1_1.0-r0 do_fetch: Failed to fetch URL git://github.com/smaeul/u-boot.git;protocol=https;branch=d1-wip, attempting MIRRORS if available
ERROR: u-boot-allwinnerd1-1_1.0-r0 do_fetch: Fetcher failure: Unable to find revision 528ae9bc6c55edd3ffe642734b4132a8246ea777 in branch d1-wip even from upstream
ERROR: u-boot-allwinnerd1-1_1.0-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/smaeul/u-boot.git;protocol=https;branch=d1-wip')
ERROR: Logfile of failure stored in: /home/lucas/riscv-yocto/build/tmp/work/mangopi_mq_pro-poky-linux/u-boot-allwinnerd1/1.0/temp/log.do_fetch.2406721
ERROR: Task (/home/lucas/riscv-yocto/meta-riscv/recipes-bsp/u-boot/u-boot-allwinnerd1.bb:do_fetch) failed with exit code '1'

The same issue happen here:
https://github.com/riscv/meta-riscv/issues/445

**Comment by landgraf** [comment]
528ae9bc6c55edd3ffe642734b4132a8246ea777 is gone from the d1 uboot tree, most likely overwritten by force push.
Proper fix should go to meta-riscv.
